package ola;

import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import ola.Request;
import ola.RequestRepository;

@Controller  // This means URL's start with /demo (after Application path)
public class RequestController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private RequestRepository requestRepository;
	
	@Autowired
	private CustomerService customerService;
	
	/*@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUser (@RequestParam String name
			, @RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		
		Request n = new Request();
		n.setCustomerId(123);
		n.setDriverId(321);
		requestRepository.save(n);
		return "Saved";
	}
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<Request> getAllUsers() {
		// This returns a JSON or XML with the users
		return requestRepository.findAll();
	}*/
	
	@RequestMapping("/customer")
	public String customer(Map<String, Object> model) {
		return "customer";
	}
	
	@RequestMapping("/rideNow")
	public String rideNow(Map<String, Object> model,@RequestParam(value="customerId") Integer customerId) {		
		customerService.registerRide(customerId);
		return "successfulRide";
	}
	
	/*@RequestMapping("/driver")
	public String driver(Map<String, Object> model,@RequestParam(value="driverId") Integer driverId) {
		//CustomerService customerService = new CustomerService();
		System.out.println("DriverID"+driverId);
		return "driver";
	}*/
}
